export const Questionset = [
  {
    Number: "1",
    question: "/JEE_Mains/2021shift1/Q01.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: "2",
    question: "/JEE_Mains/2021shift1/Q02.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 3,
    question: "/JEE_Mains/2021shift1/Q03.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 4,
    question: "/JEE_Mains/2021shift1/Q04.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 5,
    question: "/JEE_Mains/2021shift1/Q05.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 6,
    question: "/JEE_Mains/2021shift1/Q06.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 7,
    question: "/JEE_Mains/2021shift1/Q07.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 8,
    question: "/JEE_Mains/2021shift1/Q08.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 9,
    question: "/JEE_Mains/2021shift1/Q09.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 10,
    question: "/JEE_Mains/2021shift1/Q10.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 11,
    question: "/JEE_Mains/2021shift1/Q11.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 12,
    question: "/JEE_Mains/2021shift1/Q12.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 13,
    question: "/JEE_Mains/2021shift1/Q13.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 14,
    question: "/JEE_Mains/2021shift1/Q14.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 15,
    question: "/JEE_Mains/2021shift1/Q15.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 16,
    question: "/JEE_Mains/2021shift1/Q16.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 17,
    question: "/JEE_Mains/2021shift1/Q17.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 18,
    question: "/JEE_Mains/2021shift1/Q18.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 19,
    question: "/JEE_Mains/2021shift1/Q19.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 20,
    question: "/JEE_Mains/2021shift1/Q20.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 21,
    question: "/JEE_Mains/2021shift1/Q21.JPG",
    answer: "1",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 22,
    question: "/JEE_Mains/2021shift1/Q22.JPG",
    answer: "440",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 23,
    question: "/JEE_Mains/2021shift1/Q23.JPG",
    answer: "25",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 24,
    question: "/JEE_Mains/2021shift1/Q24.JPG",
    answer: "75",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 25,
    question: "/JEE_Mains/2021shift1/Q25.JPG",
    answer: "25600",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 26,
    question: "/JEE_Mains/2021shift1/Q26.JPG",
    answer: "200",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 27,
    question: "/JEE_Mains/2021shift1/Q27.JPG",
    answer: "15",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 28,
    question: "/JEE_Mains/2021shift1/Q28.JPG",
    answer: "25",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 29,
    question: "/JEE_Mains/2021shift1/Q29.JPG",
    answer: "25",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 30,
    question: "/JEE_Mains/2021shift1/Q30.JPG",
    answer: "25",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 31,
    question: "/JEE_Mains/2021shift1/Q31.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 32,
    question: "/JEE_Mains/2021shift1/Q32.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 33,
    question: "/JEE_Mains/2021shift1/Q33.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 34,
    question: "/JEE_Mains/2021shift1/Q34.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 35,
    question: "/JEE_Mains/2021shift1/Q35.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 36,
    question: "/JEE_Mains/2021shift1/Q36.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 37,
    question: "/JEE_Mains/2021shift1/Q37.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 38,
    question: "/JEE_Mains/2021shift1/Q36.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 39,
    question: "/JEE_Mains/2021shift1/Q39.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 40,
    question: "/JEE_Mains/2021shift1/Q40.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 41,
    question: "/JEE_Mains/2021shift1/Q41.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 42,
    question: "/JEE_Mains/2021shift1/Q42.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 43,
    question: "/JEE_Mains/2021shift1/Q43.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 44,
    question: "/JEE_Mains/2021shift1/Q44.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 45,
    question: "/JEE_Mains/2021shift1/Q45.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 46,
    question: "/JEE_Mains/2021shift1/Q46.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 47,
    question: "/JEE_Mains/2021shift1/Q47.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 48,
    question: "/JEE_Mains/2021shift1/Q48.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 49,
    question: "/JEE_Mains/2021shift1/Q49.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 50,
    question: "/JEE_Mains/2021shift1/Q50.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 51,
    question: "/JEE_Mains/2021shift1/Q51.JPG",
    answer: "2",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 52,
    question: "/JEE_Mains/2021shift1/Q52.JPG",
    answer: "12",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 53,
    question: "/JEE_Mains/2021shift1/Q53.JPG",
    answer: "5",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 54,
    question: "/JEE_Mains/2021shift1/Q54.JPG",
    answer: "1",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 55,
    question: "/JEE_Mains/2021shift1/Q55.JPG",
    answer: "2",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 56,
    question: "/JEE_Mains/2021shift1/Q56.JPG",
    answer: "12",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 57,
    question: "/JEE_Mains/2021shift1/Q57.JPG",
    answer: "5",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 58,
    question: "/JEE_Mains/2021shift1/Q58.JPG",
    answer: "7.5",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 59,
    question: "/JEE_Mains/2021shift1/Q59.JPG",
    answer: "26",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 60,
    question: "/JEE_Mains/2021shift1/Q60.JPG",
    answer: "8",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 61,
    question: "/JEE_Mains/2021shift1/Q61.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 62,
    question: "/JEE_Mains/2021shift1/Q62.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 63,
    question: "/JEE_Mains/2021shift1/Q63.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 64,
    question: "/JEE_Mains/2021shift1/Q64.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 65,
    question: "/JEE_Mains/2021shift1/Q65.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 66,
    question: "/JEE_Mains/2021shift1/Q66.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 67,
    question: "/JEE_Mains/2021shift1/Q67.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 68,
    question: "/JEE_Mains/2021shift1/Q66.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 69,
    question: "/JEE_Mains/2021shift1/Q69.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 70,
    question: "/JEE_Mains/2021shift1/Q70.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 71,
    question: "/JEE_Mains/2021shift1/Q71.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 72,
    question: "/JEE_Mains/2021shift1/Q72.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 73,
    question: "/JEE_Mains/2021shift1/Q73.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 74,
    question: "/JEE_Mains/2021shift1/Q74.JPG",
    answer: "2",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 75,
    question: "/JEE_Mains/2021shift1/Q75.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 76,
    question: "/JEE_Mains/2021shift1/Q76.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 77,
    question: "/JEE_Mains/2021shift1/Q77.JPG",
    answer: "3",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 78,
    question: "/JEE_Mains/2021shift1/Q78.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 79,
    question: "/JEE_Mains/2021shift1/Q79.JPG",
    answer: "4",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 80,
    question: "/JEE_Mains/2021shift1/Q80.JPG",
    answer: "1",
    section: 1,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 81,
    question: "/JEE_Mains/2021shift1/Q81.JPG",
    answer: "3",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 82,
    question: "/JEE_Mains/2021shift1/Q82.JPG",
    answer: "9",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 83,
    question: "/JEE_Mains/2021shift1/Q83.JPG",
    answer: "75",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 84,
    question: "/JEE_Mains/2021shift1/Q84.JPG",
    answer: "3",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 85,
    question: "/JEE_Mains/2021shift1/Q85.JPG",
    answer: "17",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 86,
    question: "/JEE_Mains/2021shift1/Q86.JPG",
    answer: "6",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 87,
    question: "/JEE_Mains/2021shift1/Q87.JPG",
    answer: "5",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 88,
    question: "/JEE_Mains/2021shift1/Q88.JPG",
    answer: "10",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 89,
    question: "/JEE_Mains/2021shift1/Q89.JPG",
    answer: "540",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
  {
    Number: 90,
    question: "/JEE_Mains/2021shift1/Q90.JPG",
    answer: "1",
    section: 2,
    status: "notvisited",
    response: "",
    result: "",
  },
];
