import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Champ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <div id="Title">
          Welcome to Test Champ
        </div>
        <div id="mainBtnGroup">
          <h3>JEE MAINS</h3>
          <div className="btn-categories">
            <a href="/jeemain2021s1">
              <button className="btn">2021 SHIFT-1</button>
            </a>
            <a href="/jeemain2021s2">
              <button className="btn">2021 SHIFT-2</button>
            </a>
          </div>
          <h3>JEE ADVANCED</h3>
          <div className="btn-categories">
            <a href="/jeeadv2021paper1">
              <button className="btn">2021 Paper 1</button>
            </a>
            <a href="/jeeadv2021paper2">
              <button className="btn">2021 Paper 2</button>
            </a>
            <a href="/jeeadv2020paper1">
              <button className="btn">2020 Paper 1</button>
            </a>
            <a href="/jeeadv2020paper2">
              <button className="btn">2020 Paper 2</button>
            </a>
          </div>
          <h3>RRB PO</h3>
          <div className="btn-categories">
            <a href="#">
              <button className="btn">RRB PO</button>
            </a>
          </div>
          <h3>RRB CLERICAL</h3>
          <div className="btn-categories">
            <a href="#">
              <button className="btn">JEE Advanced</button>
            </a>
          </div>
          <h3>IBPS PO</h3>
          <div className="btn-categories">
            <a href="#">
              <button className="btn">JEE Advanced</button>
            </a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
