import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jobs and Tests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gray-50 p-4">
        <h1 className="text-3xl font-bold text-center mb-6">JOBS</h1>

        <div className="grid grid-cols-1 md:grid-cols-[3fr_1fr] gap-6">
          {/* LEFT: JOB LISTINGS */}
          <div className="space-y-4">
            {/* Job Card */}
            <div className="flex bg-white shadow rounded overflow-hidden">
              <div className="bg-gradient-to-r from-blue-900 to-red-600 text-white font-bold p-4 w-48 flex items-center">
                <span>ARMED FORCES MEDICAL SERVICES</span>
              </div>
              <div className="p-4">
                <a
                  href="#"
                  className="text-blue-700 font-semibold hover:underline"
                >
                  Armed Forces Medical Services Recruitment – 400 Posts
                </a>
                <p className="text-gray-700 mt-2">
                  Armed Forces Medical Services (AFMS) has released an
                  employment notification...
                </p>
                <p className="mt-2">
                  <span className="bg-purple-700 text-white px-2 py-1 text-sm rounded">
                    Last date: 12/05/2025
                  </span>
                  <span className="ml-2">
                    | Notification:{" "}
                    <a href="#" className="text-blue-600 underline">
                      Click here
                    </a>
                  </span>
                  <span className="ml-2">
                    | Apply:{" "}
                    <a href="#" className="text-blue-600 underline">
                      Click here
                    </a>
                  </span>
                </p>
              </div>
            </div>

            {/* Another Job Card */}
            {/* Repeat similar blocks for other jobs */}
          </div>

          {/* RIGHT: MOCK TEST SECTION */}
          <div className="bg-white shadow rounded p-4 space-y-4">
            <h2 className="text-xl font-bold text-center">Mock Test</h2>
            <Link href="/Instructions">
              <div
                id="Title"
                className="font-bold text-white bg-indigo-700 text-center p-5 hover:cursor-pointer hover:bg-green-700"
              >
                START TEST
              </div>
            </Link>
            <div>
              <h3 className="bg-red-600 text-white font-semibold p-2">
                JEE MAINS
              </h3>
              <ul className="border border-gray-200 divide-y divide-gray-200">
                <li className="p-2 hover:bg-gray-100">
                  <a href="#" className="text-blue-600 underline">
                    2021 SHIFT-1
                  </a>
                </li>
                <li className="p-2 hover:bg-gray-100">
                  <a href="#" className="text-blue-600 underline">
                    2021 SHIFT-2
                  </a>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="bg-red-600 text-white font-semibold p-2">
                JEE ADVANCED
              </h3>
              <ul className="border border-gray-200 divide-y divide-gray-200">
                <li className="p-2 hover:bg-gray-100">
                  <a href="#" className="text-blue-600 underline">
                    2021 SHIFT-1
                  </a>
                </li>
                <li className="p-2 hover:bg-gray-100">
                  <a href="#" className="text-blue-600 underline">
                    2021 SHIFT-2
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
