export const Questionset = [
    {
        number: "1",
        question: "Which of the following is correct about HTML?",
        options: ["HTML uses User Defined Tags", "HTML uses tags defined within the language", "Both A and B", "None of the above"],
        status: "notvisited",
        solution: "HTML uses tags defined within the language",
        answer: "2",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "2",
        question: "How many sizes of headers are available in HTML by default?",
        options: ["5", "1", "3", "6"],
        status: "notvisited",
        solution: "6",
        answer: "4",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "3",
        question: "What  is the smallest header in HTML by default?",
        options: ["h1", "h2", "h6", "h4"],
        status: "notvisited",
        solution: "h6",
        answer: "3",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "4",
        question: "What are the types of lists available in HTML?",
        options: ["Ordered, Unordered lists", "Bulleted, Numbered list", "Named, Unnamed lists", "None of the above"],
        status: "notvisited",
        solution: "Ordered, Unorderd lists",
        answer: "1",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "5",
        question: "How to create an ordered list in HTML?",
        options: ["<ul>", "<ol>", "<href>", "<b>"],
        status: "notvisited",
        solution: "<ol>",
        answer: "2",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "6",
        question: "HTML files are saved by default with the extension?",
        options: [".html", ".h", ".ht", "None of the above"],
        status: "notvisited",
        solution: ".html",
        answer: "1",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "7",
        question: "We enclose HTML tags within?",
        options: ["{}", "<>", "!!", "None of the above"],
        status: "notvisited",
        solution: "<>",
        answer: "2",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "8",        
        question: "What is the effect of the <b> tag?",
        options: ["It converts the text within it to bold font", "It is used to write black-colored font", "It is used to change the font size", "None of the above"],
        status: "notvisited",
        solution: "It converts the text within it to bold font",
        answer: "1",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "9",
        question: "What does the abbreviation HTML stand for?",
        options: ["HyperText Markup Language", "HigherText Markup Language", "HyperText Markdown Language", "None of the above"],
        status: "notvisited",
        solution: "HyperText Markup Language",
        answer: "1",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "10",
        question: "How to display preformatted text in HTML?",
        options: ["<p>", "<pre>", "<hr>", "All of the above"],
        status: "notvisited",
        solution: "<pre>",
        answer: "2",
        response: "",
        result: "",
        section: "HTML"
    },
    {
        number: "11",
        question: "Which of the following is the correct syntax for referring the external style sheet?",
        options: ["<style src = example.css>",'<style src = "example.css" >',"   <stylesheet> example.css </stylesheet>",'<link rel="stylesheet" type="text/css" href="example.css">'],
        status: "notvisited",
        solution: '<link rel="stylesheet" type="text/css" href="example.css">',
        answer: "4",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "12",
        question: " The property in CSS used to change the background color of an element is -",
        options: ["bgcolor", "color", "background-color", "All of the above"],
        status: "notvisited",
        solution: "background-color",
        answer: "c",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "13",
        question: "The HTML attribute used to define the inline styles is -",
        options: ["style", "styles", "class", "None of the above"],
        status: "notvisited",
        solution: "style",
        answer: "1",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "14",
        question: "The CSS property used to make the text bold is -",
        options: ["font-weight : bold"," weight: bold","font: bold","style: bold"],
        status: "notvisited",
        solution: "font-weight: bold",
        answer: "1",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "15",
        question: "Are the negative values allowed in padding property?",
        options: ["Yes", "No", "Can't say", "May be"],
        status: "notvisited",
        solution: "No",
        answer: "1",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "16",
        question: "Which of the following is used to specify the subscript of text using CSS?",
        options: ["vertical-align: sub","vertical-align: super","vertical-align: subscript","None of the above"],
        status: "notvisited",
        solution: "vertical-align: sub",
        answer: "1",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "17",
        question:  "Which of the following CSS property is used to specify the space between every letter inside an element?",
        options: ["alpha-spacing","character-spacing","letter-spacing","alphabet-spacing"],
        status: "notvisited",
        solution: "letter-spacing",
        answer: "c",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "18",
        question: "The CSS property used to specify whether the text is written in the horizontal or vertical direction?",
        options: ["writing-mode","text-indent","word-break","None of the above"],
        status: "notvisited",
        solution: "writing-mode",
        answer: "a",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "19",
        question: "Which of the following syntax is correct in CSS to make each word of a sentence start with a capital letter?",
        options: ["text-style : capital;","transform : capitalize;","text-transform : capital;","text-transform : capitalize;"],
        status: "notvisited",
        solution: "text-transform: capitalize",
        answer: "4",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "20",
        question: "Which of the following is the correct syntax to select the p siblings of a div element?",
        options: ["p","div + p","div p","div ~ p"],
        status: "notvisited",
        solution: "div ~ p",
        answer: "4",
        response: "",
        result: "",
        section: "CSS"
    },
    {
        number: "21",
        question: "Javascript is an _______ language?",
        options: ["Object-oriented", "Object-based", "Procedural", "None of the above"],
        status: "notvisited",
        solution: "Object-oriented",
        answer: "1",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "22",
        question: "Which of the following keywords is used to define a variable in Javascript?",
        options: ["var", "let", "Both A and B", "None of the above"],
        status: "notvisited",
        solution: "Both A and B",
        answer: "3",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "23",
        question: "In JavaScript, what is a block of statement?",
        options: ["Conditional block","block that combines a number of statements into a single compound statement","both conditional block and a single statement","block that contains a single statement"],
        status: "notvisited",
        solution: "block that combines a number of statements into a single compound statement",
        answer: "2",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "24",
        question: "Which of the following variables takes precedence over the others if the names are the same?",
        options: ["Global variable","The local element","The two of the above","   None of the above"],
        status: "notvisited",
        solution: "The local element",
        answer: "2",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "25",
        question: " Which one of the following is the correct way for calling the JavaScript code?",
        options: ["Preprocessor", "Triggering Event", "RMI", "Function/Method"],
        status: "notvisited",
        solution: "Function/ Method",
        answer: "4",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "26",
        question: " When there is an indefinite or an infinite value during an arithmetic computation in a program, then JavaScript prints______.",
        options: ["Prints an exception error", "Prints an overflow error", 'Displays "Infinity"', "Prints the value as such"],
        status: "notvisited",
        solution: 'Displays "Infinity"',
        answer: "3",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "27",
        question: "Which of the following givenfunctions of the Number Object formats a number with a different number of digits to the right of the decimal?",
        options: ["toExponential()","toFixed()","toPrecision()","toLocaleString()"],
        solution: "toFixed()",
        status: "notvisited",
        answer: "2",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "28",
        question: "Which of the following function of the String object returns the character in the string starting at the specified position via the specified number of characters?",
        options: ["slice()","split()","substr()","search()"],
        status: "notvisited",
        solution: "substr()",
        answer: "1",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "29",
        question: "Which of the following scoping type does JavaScript use?",
        options: ["Sequential","Segmental","Lexical","Literal"],
        status: "notvisited",
        solution: "Lexical",
        answer: "3",
        response: "",
        result: "",
        section: "Javascript"
    },
    {
        number: "30",
        question: " Which of the following is not an error in JavaScript?",
        options: ["Missing of Bracket","Division by zero","Syntax error","Missing of semicolons"],
        status: "notvisited",
        solution: "Division by zero",
        answer: "2",
        response: "",
        result: "",
        section: "Javascript"
    },
   
]